---
- name: install required packages
  ansible.builtin.apt:
    name: "{{ osm_required_packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600

- name: Create directory osm/src
  ansible.builtin.file:
    path: /opt/osm/src
    state: directory
    recurse: yes
    owner: vagrant
    group: vagrant

- name: Create directory osm/data
  ansible.builtin.file:
    path: /opt/osm/data
    state: directory
    recurse: yes
    owner: vagrant
    group: vagrant

- name: Git openstreetmap-carto
  ansible.builtin.git:
    repo: 'https://github.com/gravitystorm/openstreetmap-carto.git'
    dest: /opt/osm/src/openstreetmap-carto
    #version: latest

- name: Create directory /opt/osm/src/openstreetmap-carto/symbols/custom_seamark_mooring
  ansible.builtin.file:
    path: /opt/osm/src/openstreetmap-carto/symbols/custom_seamark_mooring
    state: directory
    recurse: yes
    owner: vagrant
    group: vagrant

- name: Add custom_seamark_mooring.mss to carto /opt/osm/src/openstreetmap-carto/style
  ansible.builtin.copy:
    src: custom_seamark_mooring.mss
    dest: /opt/osm/src/openstreetmap-carto/style/custom_seamark_mooring.mss
    owner: vagrant
    group: vagrant
    mode: 0644

# Icons taken from https://wiki.openstreetmap.org/wiki/Tag:seamark:type%3Dmooring
- name: Add dolphin icon to /opt/osm/src/openstreetmap-carto/symbols/custom_seamark_mooring
  ansible.builtin.copy:
    src: Dolphin.png
    dest: /opt/osm/src/openstreetmap-carto/symbols/custom_seamark_mooring/dolphin.png
    owner: vagrant
    group: vagrant
    mode: 0644

- name: Add bollard icon to /opt/osm/src/openstreetmap-carto/symbols/custom_seamark_mooring
  ansible.builtin.copy:
    src: MBollard.png
    dest: /opt/osm/src/openstreetmap-carto/symbols/custom_seamark_mooring/bollard.png
    owner: vagrant
    group: vagrant
    mode: 0644

- name: Add pile icon to /opt/osm/src/openstreetmap-carto/symbols/custom_seamark_mooring
  ansible.builtin.copy:
    src: Post.png
    dest: /opt/osm/src/openstreetmap-carto/symbols/custom_seamark_mooring/pile.png
    owner: vagrant
    group: vagrant
    mode: 0644

- name: Add post icon to /opt/osm/src/openstreetmap-carto/symbols/custom_seamark_mooring
  ansible.builtin.copy:
    src: MBollard.png
    dest: /opt/osm/src/openstreetmap-carto/symbols/custom_seamark_mooring/post.png
    owner: vagrant
    group: vagrant
    mode: 0644

- name: Add custom_seamarks.mss Style to carto project.mml
  ansible.builtin.lineinfile:
    path: /opt/osm/src/openstreetmap-carto/project.mml
    regexp: '^  - style/custom_seamarks.mss'
    insertafter: '  - style/tourism.mss'
    line: '  - style/custom_seamark_mooring.mss'

- name: Add custom_seamark_mooring Layer to carto project.mml
  ansible.builtin.blockinfile:
    path: /opt/osm/src/openstreetmap-carto/project.mml
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    #insertafter: "Layer:"
    block: |2
        - id: seamark-moorings
          geometry: point
          <<: *extents
          Datasource:
            <<: *osm2pgsql
            table: |-
              (SELECT
                way,
                tags->'seamark:mooring:category' AS category
              FROM planet_osm_point
              WHERE
                tags @> 'seamark:type=>mooring'
              AND
                (
                  tags @> 'seamark:mooring:category=>dolphin'
                OR
                  tags @> 'seamark:mooring:category=>bollard'
                OR
                  tags @> 'seamark:mooring:category=>pile'
                OR
                  tags @> 'seamark:mooring:category=>post'
                )
              ) AS seamark_moorings
          properties:
            minzoom: 15
            maxzoom: 22

- name: Download schleswig-holstein-latest.osm.pbf
  ansible.builtin.get_url:
    url: https://download.geofabrik.de/europe/germany/schleswig-holstein-latest.osm.pbf
    dest: /opt/osm/data/data.osm.pbf
    mode: '0755'

- name: Reduce the osm.pbf data to Kieler Förde (10.094472 , 54.300117 | 10.327428 , 54.453653 )
  ansible.builtin.shell: osmconvert data.osm.pbf -b=10.094472,54.300117,10.327428,54.453653 -o=reduced_data.osm.pbf
  args:
    executable: /bin/bash
    creates: reduced_data.osm.pbf
    chdir: /opt/osm/data/

- name: Install "carto" node.js package globally.
  community.general.npm:
    name: carto
    global: true

- name: Create the mapnik.xml
  ansible.builtin.shell: carto project.mml > mapnik.xml
  args:
    executable: /bin/bash
    creates: mapnik.xml
    chdir: /opt/osm/src/openstreetmap-carto/

- name: Import openstreetmap data
  ansible.builtin.shell: sudo -u _renderd osm2pgsql -d gis --create --slim  -G --hstore --tag-transform-script src/openstreetmap-carto/openstreetmap-carto.lua -C 2500 --number-processes 1 -S src/openstreetmap-carto/openstreetmap-carto.style data/reduced_data.osm.pbf
  args:
    executable: /bin/bash
    chdir: /opt/osm/
  #become: yes
  #become_user: _renderd

- name: Add extra indexes
  ansible.builtin.shell: sudo -u _renderd psql -d gis -f indexes.sql
  args:
    executable: /bin/bash
    chdir: /opt/osm/src/openstreetmap-carto/
  #become: yes
  #become_user: _renderd

- name: Create directory openstreetmap-carto/data
  ansible.builtin.file:
    path: /opt/osm/src/openstreetmap-carto/data
    state: directory
    recurse: yes
    owner: _renderd
    group: _renderd

- name: Shapefile download
  ansible.builtin.shell: sudo -u _renderd scripts/get-external-data.py
  args:
    executable: /bin/bash
    chdir: /opt/osm/src/openstreetmap-carto/
  #become: yes
  #become_user: _renderd

- name: Install fonts
  ansible.builtin.shell: scripts/get-fonts.sh
  args:
    executable: /bin/bash
    chdir: /opt/osm/src/openstreetmap-carto/
  # crrently some of te download urls are responding with an outdated certificate
  ignore_errors: true

- name: insert/update HTML surrounded by custom markers after <body> line
  blockinfile:
    path: /etc/renderd.conf
    marker: "# S2O Block"
    insertafter: "; ADD YOUR LAYERS:"
    content: |
      [s2o]
      URI=/hot/
      XML=/opt/osm/src/openstreetmap-carto/mapnik.xml
      HOST=osm.lokal
      TILESIZE=256
      MAXZOOM=20

- name: Set environmet
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/renderd.service
    regexp: '^Environment'
    insertafter: '^[Service]'
    line: 'Environment=G_MESSAGES_DEBUG=all'

- name: Just force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart service renderd
  ansible.builtin.systemd:
    name: renderd.service
    state: restarted

- name: Reload service httpd, in all cases
  ansible.builtin.systemd:
    name: apache2.service
    state: restarted

- name: Download file from a file path
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/SomeoneElseOSM/mod_tile/switch2osm/extra/sample_leaflet.html
    dest: /var/www/html/index.html

- name: Set domain to
  ansible.builtin.replace:
    path: /var/www/html/index.html
    regexp: '127.0.0.1'
    replace: 'osm.lokal'

...
