---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  - name: "Searching for force_color_prompt"
    lineinfile:
      path: /root/.bashrc
      line: 'force_color_prompt=yes'
      state: present
    check_mode: true
    register: presence

  - name: Assert presence is unchanged
    ansible.builtin.assert:
      that: presence.changed == false
...
