---

- name: install required packages
  ansible.builtin.apt:
    name: "{{ required_packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600

- name: install required python packages
  ansible.builtin.pip:
    name: "{{ required_python_packages }}"
    extra_args: --upgrade
    executable: pip3

- name: copy ssh_config /home/vagrant/.ssh/config
  ansible.builtin.copy:
    src: ssh_config
    dest: /home/vagrant/.ssh/config
    owner: vagrant
    group: vagrant
    mode: 0644

...
