---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  - name: Get Service Status
    ansible.builtin.systemd:
      name: "mailhog.service"
    register: mailhog_service_status

  # - name: dump mailhog service
  #   ansible.builtin.debug:
  #     var: mailhog_service_status

  - name: Assert mailhog.service is enabled
    ansible.builtin.assert:
      that: mailhog_service_status.status.ActiveState == "active"
...
