---
- hosts: all
  become: true
  become_method: sudo

  vars:
    postgresql_listen: "0.0.0.0"
    postgresql_additional_packages:
    - postgis
    - osm2pgsql
    postgresql_databases:
    - name: test
      encoding: UTF-8
      state: present
      schemas:
      - name: schemaone
        state: present
      - name: schematwo
        state: present
      extensions:
      - name: postgis
        state: present
      - name: hstore
        state: present
    postgresql_users:
    - name: testuser
      password: 1234test
      state: present
      privileges:
      - database: test
        privs: "All"
        state: present
      hosts:
      - cidr: 0.0.0.0/0
        database: test
        state: present

  roles:
  - andrelohmann.root_colored_prompt
  - ansible-role-postgresql
...
