---
- hosts: all
  become: true
  become_method: sudo

  vars:
    required_packages:
    - git
    - tcptraceroute
    - nmap
    - net-tools
    - htop
    - jq
    - python3-pip
    - apache2
    - osmium-tool
    required_python_packages: []
    mailpit_proxy_apache: true
    mailpit_proxy_domain: mail.osm.lokal
    mailpit_proxy_port: 80
    pgadmin_domain: pgadmin.osm.lokal
    pgadmin_email: admin@pgadmin.osm.lokal
    pgadmin_password: admin

    #postgresql_listen: "192.168.56.101"
    postgresql_listen: "0.0.0.0"
    postgresql_additional_packages:
    - postgis
    - osm2pgsql
    postgresql_databases:
    - name: gis
      encoding: UTF-8
      state: present
      schemas: []
      extensions:
      - name: postgis
        state: present
      - name: hstore
        state: present
    postgresql_users:
    - name: _renderd
      password: renderd.secret
      state: present
      privileges:
      - database: gis
        privs: "All"
        state: present
      hosts:
      - cidr: 0.0.0.0/0
        database: gis
        state: present
      - cidr: localhost
        database: gis
        state: present

  pre_tasks:
  - name: check for file custom_vars.yml
    stat:
      path: custom_vars.yml
    register: stat_custom_vars
  - name: load custom vars, if existent
    include_vars:
      file: custom_vars.yml
    when: stat_custom_vars.stat.exists

  roles:
  - andrelohmann.root_colored_prompt
  - default_tasks
  - andrelohmann.postgresql
  - osm_tile_server
  - andrelohmann.mailpit
  - pgadmin

  #tasks:

  #- name: restart prometheus after each change
  #  systemd:
  #    name: prometheus
  #    state: restarted

...
