---
- hosts: all
  become: true
  become_method: sudo

  vars:
    mailhog_smtp_port: 1025
    mailhog_web_port: 8025
    mailhog_path: /opt/mailhog
    mailhog_release: v1.0.1
    mailhog_proxy_apache: true
    mailhog_proxy_domain: mailhog.lokal

  roles:
  - andrelohmann.root_colored_prompt
  - ansible-role-mailhog
...
