---
galaxy_info:
  role_name: docker
  author: andrelohmann
  description: ansible galaxy role to deploy docker
  company: smartformer UG

  license: MIT

  min_ansible_version: 2.7

  platforms:
    - name: Debian
      versions:
      - jessie
      - stretch
      - buster
      - bullseye
    - name: Ubuntu
      versions:
      - bionic
      - focal

  galaxy_tags:
  - docker

dependencies: []
...
