---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  - name: postgresql restart
    systemd:
      name: postgresql
      state: restarted

  - name: Get Service Status
    ansible.builtin.systemd:
      name: "postgresql.service"
    register: pg_service_status

  # - name: dump postgresql service
  #   ansible.builtin.debug:
  #     var: pg_service_status

  - name: Assert postgresql.service is enabled
    ansible.builtin.assert:
      that: pg_service_status.status.ActiveState == "active"
...
